project:
  type: website
  output-dir: docs

website:
  title: "Nathaniel Hurst"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - CV.qmd
    tools: 
      - icon: github
        href: https://github.com/NateHurst
      - icon: linkedin
        href: https://www.linkedin.com/in/nathaniel-hurst-a6b106245/
      - icon: envelope
        href: mailto:nhurst0003@gmail.com
      
format:
  html:
    theme:
      light: cobalt
      dark: cobalt    
    fontcolor: "#FEFEFE"
    fontsize: 1.4rem
    css: styles.css
    toc: true



